const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'); process.chdir(root); const elements=new Map(), events=[];
class Element{constructor(){this.style={};this.dataset={};this.innerHTML='';this.textContent='';this.src='';this.events={};this.classes=new Set();this.classList={add:x=>this.classes.add(x),remove:x=>this.classes.delete(x),contains:x=>this.classes.has(x),toggle:(x,on)=>on?this.classes.add(x):this.classes.delete(x)}} setAttribute(n,v){this[n]=v} addEventListener(n,f){this.events[n]=f} querySelector(s){return get(s)} click(){this.events.click?.();this.onclick?.()}}
function get(s){if(!elements.has(s))elements.set(s,new Element());return elements.get(s)}
const noop=()=>{};const ctx=new Proxy({measureText:t=>({width:String(t).length*7})},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});
const canvas=new Element();Object.assign(canvas,{width:1100,height:650,getContext:()=>ctx,getBoundingClientRect:()=>({left:10,top:20,width:550,height:325}),addEventListener:(n,f)=>events.push([n,f])});elements.set('#gameCanvas',canvas);
class FakeImage{set src(v){this._src=v;this.width=256;this.height=256;Promise.resolve().then(()=>this.onload?.())}get src(){return this._src}}
const storage=new Map();let timer=0;const sandbox={console,document:{querySelector:get,querySelectorAll:()=>[],addEventListener:()=>{}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Image:FakeImage,performance:{now:()=>0},requestAnimationFrame:()=>{},setTimeout:()=>++timer,clearTimeout:()=>{},Math:Object.create(Math)};sandbox.Math.random=()=>.4;sandbox.window=sandbox;sandbox.addEventListener=()=>{};vm.createContext(sandbox);
for(const f of ['data/game-data.js','data/sprite-data.js','data/sprite-metrics.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox);
let source=fs.readFileSync(path.join(root,'js/game.js'),'utf8').replace('  // ---------- init ----------',`  window.TEST={state,images,startLevel,spawnEnemy,placeUnit,cellFromPointer,applyDamage,updateUnits,updateEnemies,updateEffects,updateWaveSystem,updateMetabolism,useAbility,activateAntibody,draw,drawSprite,fallbackAsset,preload,frame,togglePause,handleCanvasPointer,getUnlocked,getQuiz,unlockThrough,saveQuiz,GRID};\n  // ---------- init ----------`);vm.runInContext(source,sandbox);
const T=sandbox.TEST,D=sandbox.IMMUNO_DATA; const passed=[];function check(name,fn){fn();passed.push(name)}
function reset(level=5){T.startLevel(level);T.state.running=true;T.state.paused=false;T.state.energy=10000;T.state.intermissionUntil=999999;T.state.waveIndex=-1;get('#modal').classList.add('hidden')}
function place(type,row,col){T.state.selectedUnit=type;T.placeUnit(row,col);return T.state.units.at(-1)}function enemy(type,row,x){T.spawnEnemy(type,row);let e=T.state.enemies.at(-1);e.x=x;return e}
(async()=>{await T.preload();
check('pointer mapping',()=>{let c=T.cellFromPointer({clientX:10+168*.5,clientY:20+146*.5});assert.equal(c.c,0);assert.equal(c.r,0)});
check('placement responsive and inspectable',()=>{reset(1);T.state.energy=260;let u=place('rbc',0,0);assert.equal(T.state.energy,210);assert.equal(T.state.selectedPlacedId,u.id);assert.ok(u.actionUntil>T.state.elapsed);assert.ok(T.state.effects.some(e=>e.type==='pulse'));T.placeUnit(0,0);assert.equal(T.state.units.length,1)});
check('primed production responds quickly',()=>{reset();let r=place('rbc',0,0),p=place('plasma',0,1);let o=T.state.oxygen,n=T.state.nutrient;for(let i=0;i<150;i++){T.state.elapsed+=.01;T.updateUnits(.01)}assert.ok(T.state.oxygen>o);assert.ok(T.state.nutrient>n)});
check('b cell visibly tags recognized target',()=>{reset();let b=place('b_cell',0,0);T.state.antigenSamples.circle=3;let e=enemy('coccus',0,800);b.resourceTimer=6.5;T.updateUnits(.01);assert.ok(T.state.projectiles.some(p=>p.source==='b_cell'));T.updateEffects(.4);assert.ok(e.taggedUntil>T.state.elapsed)});
check('platelet closes wound with fibrin feedback',()=>{reset(1);let p=place('platelet',1,6);assert.ok(!T.state.wounds.has('1,6'));assert.ok(p.maxHp>D.units.platelet.hp);assert.ok(T.state.effects.some(e=>e.item==='fibrin'))});
check('projectile damage arrival',()=>{reset();let u=place('nk_cell',1,2),e=enemy('free_virus',1,u.x+130),hp=e.hp;T.updateUnits(.01);assert.equal(e.hp,hp);T.updateEffects(.25);assert.ok(e.hp<hp)});
check('all abilities execute',()=>{reset();let e=enemy('coccus',0,700);e.taggedUntil=100;T.state.signal=100;for(const k of Object.keys(D.abilities))T.useAbility(k);assert.ok(T.state.buffs.cytokineUntil>0);assert.ok(T.state.buffs.feverUntil>0)});
check('five level seeded simulation finite',()=>{for(let level=1;level<=5;level++){reset(level);T.state.intermissionUntil=0;for(let r=0;r<5;r++){place('rbc',r,0);place('neutrophil',r,3);place('platelet',r,5)}for(let i=0;i<900&&T.state.running;i++){let dt=.05;T.state.elapsed+=dt;T.updateEffects(dt);T.updateUnits(dt);T.updateEnemies(dt);if(T.state.running){T.updateWaveSystem();T.updateMetabolism(dt)}}assert.ok(Number.isFinite(T.state.energy));assert.ok(Number.isFinite(T.state.tissue));assert.ok(T.state.tissue>=0)}});
check('pointer event pipeline installed',()=>{const names=events.map(x=>x[0]);assert.ok(names.includes('pointerdown'));assert.ok(names.includes('pointermove'));assert.ok(names.includes('pointerleave'))});
console.log(JSON.stringify({passed:passed.length,checks:passed},null,2));})().catch(e=>{console.error(e);process.exit(1)});
