const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),elements=new Map(),keyHandlers=[];
let doc;
function get(id){if(!elements.has(id)){const classes=new Set();elements.set(id,{value:0,textContent:'',inert:false,events:{},classList:{add:s=>classes.add(s),remove:s=>classes.delete(s),contains:s=>classes.has(s)},setAttribute(k,v){this[k]=v},focus(){doc.activeElement=this},addEventListener(k,fn){this.events[k]=fn},querySelectorAll(){return ['#musicVolume','#musicMuteBtn','#settingsSfxVolume','#settingsSfxMuteBtn','#testSfxBtn','#closeSettingsBtn'].map(get)}});}return elements.get(id);}
doc={activeElement:get('#menuSettingsBtn'),querySelector:get};get('#audioSettings').classList.add('hidden');
const sfx={volume:.55,muted:false,setVolume(v){this.volume=v;sandbox.IMMUNO_SETTINGS.refresh()},setMuted(v){this.muted=v;sandbox.IMMUNO_SETTINGS.refresh()},unlock:()=>Promise.resolve(),play(){}};
const music={volume:.35,muted:false,setVolume(v){this.volume=v;sandbox.IMMUNO_SETTINGS.refresh()},setMuted(v){this.muted=v;sandbox.IMMUNO_SETTINGS.refresh()}};
const sandbox={document:doc,console,IMMUNO_SOUND:sfx,IMMUNO_MUSIC:music,addEventListener:(k,fn,capture)=>keyHandlers.push({k,fn,capture})};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'js/settings.js'),'utf8'),sandbox);
const checks=[],check=(name,fn)=>{fn();checks.push(name)};
check('Menu settings opens as a modal and focuses the music slider',()=>{get('#menuSettingsBtn').events.click();assert.equal(get('#app').inert,true);assert.equal(get('#modal').inert,true);assert.equal(doc.activeElement,get('#musicVolume'));assert.equal(get('#audioSettings').classList.contains('hidden'),false)});
check('Each slider changes only its own audio channel',()=>{get('#musicVolume').events.input({target:{value:'18'}});assert.equal(music.volume,.18);assert.equal(sfx.volume,.55);get('#settingsSfxVolume').events.input({target:{value:'76'}});assert.equal(music.volume,.18);assert.equal(sfx.volume,.76);assert.equal(get('#settingsSfxValue').textContent,'76%')});
check('Music and SFX mute are independent and reflected in aria state',()=>{get('#musicMuteBtn').events.click();assert.equal(music.muted,true);assert.equal(sfx.muted,false);get('#settingsSfxMuteBtn').events.click();assert.equal(get('#settingsSfxMuteBtn')['aria-pressed'],'true')});
const handle=keyHandlers[0];check('ESC is captured before gameplay and restores focus without resuming it',()=>{let stopped=false,prevented=false;assert.equal(handle.capture,true);handle.fn({code:'Escape',preventDefault(){prevented=true},stopImmediatePropagation(){stopped=true}});assert.ok(stopped&&prevented);assert.equal(get('#audioSettings').classList.contains('hidden'),true);assert.equal(get('#app').inert,false);assert.equal(doc.activeElement,get('#menuSettingsBtn'))});
check('Pause settings preserves an already inert underlying dialog',()=>{get('#modal').inert=true;doc.activeElement=get('#pauseSettingsBtn');get('#pauseSettingsBtn').events.click();get('#closeSettingsBtn').events.click();assert.equal(get('#modal').inert,true);assert.equal(doc.activeElement,get('#pauseSettingsBtn'))});
check('Tab and Shift Tab stay within the audio dialog',()=>{get('#menuSettingsBtn').events.click();get('#closeSettingsBtn').focus();handle.fn({code:'Tab',preventDefault(){},stopImmediatePropagation(){}});assert.equal(doc.activeElement,get('#musicVolume'));handle.fn({code:'Tab',shiftKey:true,preventDefault(){},stopImmediatePropagation(){}});assert.equal(doc.activeElement,get('#closeSettingsBtn'))});
const report={passed:checks.length,checks,browserTest:false};fs.writeFileSync(path.join(root,'docs/TEST_SETTINGS_v0.9.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
